name: "CD Workflow"
env:
  FLUTTER_VERSION: "3.3.9"
  FLUTTER_CHANNEL: "stable"
on:
  pull_request:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    name: Run QA Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
        name: Install Dependencies
      - run: flutter pub get
        name: format all file in the libe directory
      - run: flutter format lib/
        name: Analyze Code, searching for problems and errors
      - run: flutter analyze --no-pub
        name: Generate necessary files and delete conflicting files
      - run: flutter pub run build_runner build --delete-conflicting-outputs
        name: Build APk
      - run: flutter build apk --debug --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
        name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}